parameters:
  - name: registryDocker
  - name: tagBuild

steps:
- script: |
    echo "Construindo imagem Docker" \
    && docker build -t ${{ parameters.registryDocker }}:${{ parameters.tagBuild }} -f devops/Dockerfile . \
    && echo "Publicando imagem Docker" \
    && docker push ${{ parameters.registryDocker }}:${{ parameters.tagBuild }}
  
  displayName: 'Build and Publish Docker Image'
