parameters:
  - name: dockerImage

steps:
- script: |
    docker login -u artifact_service_account -p '4gkABd8C6ErdaSXJwlUd' docker.mj.gov.br
    docker run -i --rm \
    -v $(pwd):/opt/app \
    --entrypoint="/bin/sh" \
    ${{ parameters.dockerImage }} \
    -c 'cd /opt/app && npm set registry http://artifact.mj.gov.br/repository/npm-group/ && npm install -g @angular/cli@11.2.18 \
    && export NODE_OPTIONS=\"--max-old-space-size=5120\" \
    && npm ci \
    && ng build -c cloud'

    sudo chown -R AzDevOps:AzDevOps ./dist
    cd dist/sgcf && tar -czvf deployment.tar.gz *

  displayName: 'Build Application'
