parameters:
  - name: dockerImage

steps:
- script: |
    docker login -u usuarioFIXO -p 'VARIAVEL_AMBIENTE' dockerrod.com.br
    docker run -i --rm \
    -v $(pwd):/opt/app \
    --entrypoint="/bin/sh" \
    ${{ parameters.dockerImage }} \
    -c 'cd /opt/app && npm set registry http://dockerrod.com.br/repository/npm-group/ && npm install -g @angular/cli@11.2.18 \
    && export NODE_OPTIONS=\"--max-old-space-size=5120\" \
    && npm ci \
    && ng build -c cloud'

    sudo chown -R AzDevOps:AzDevOps ./dist
    cd dist/doc && tar -czvf deployment.tar.gz *

  displayName: 'Build Application'
