apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generico.fullname" . }}
  labels:
    {{- include "generico.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generico.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        deploymentTime: {{ now | date "20060102150405" | quote }}      
        {{- with .Values.podAnnotations }}        
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "generico.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "generico.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            {{- toYaml .Values.deployment.ports | nindent 12 }}
          {{ if .Values.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.deployment.livenessProbe | nindent 12 }}
          {{ end }}
          {{ if .Values.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.deployment.readinessProbe | nindent 12 }}
          {{ end }}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 20m
              memory: 64Mi
          {{ if .Values.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.deployment.volumeMounts | nindent 12 }}
          {{ end }}
          {{ if .Values.deployment.env }}
          env: 
            {{- toYaml .Values.deployment.env | nindent 12 }}
          {{ end }}
      {{ if .Values.deployment.volumes }}      
      volumes: 
        {{- toYaml .Values.deployment.volumes | nindent 6 }}
     {{ end }}         
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
