{{- range .Values.secrets }}
apiVersion: v1
data:
  {{- toYaml .data | nindent 2 }}
stringData:
{{- toYaml .stringData | nindent 2 }}        
kind: Secret
metadata:
  name: {{ .name }}
---  
{{- end }}


